export default AppImages = {
    SplashScreenLogo: require('../assets/images/splashScreenLogo.png'),
    SplashScreenBackground: require('../assets/images/splashScreenBackground.png'),
    SplashScreenVehicle: require('../assets/images/splashScreenVehicle.png'),
    SplashUpperBackground: require('../assets/images/splashUpperBackground.png'),
    DropDownButton: require('../assets/images/dropDownButton.png'),
    OnboardingImg1: require('../assets/images/onbardingImg1.png'),
    OnboardingImg2: require('../assets/images/onbardingImg2.png'),
    OnboardingImg3: require('../assets/images/onboardingImg3.png'),
    OnboardingBack1: require('../assets/images/onboardingback1.png'),
    OnboardingBack2: require('../assets/images/onboardingback2.png'),
    OnboardingBack3: require('../assets/images/onboardingback3.png'),
    EnterNumberScreenImg: require('../assets/images/EnterNumberScreenImg.png'),
    IndiaFlag: require('../assets/images/IndiaFlag.png'),
    whatsappIcon: require('../assets/images/whatsapp.png'),
    SmsIcon: require('../assets/images/sms.png'),
    eyeClose: require('../assets/images/eye-slash.png'),
    eyeOpen: require('../assets/images/eye.png'),
    verified: require('../assets/images/verified.png'),
    location: require('../assets/images/location.png'),
    Bell: require('../assets/images/bell.png'),
    arrowDown: require('../assets/images/arrow-down.png'),
    ParsalPlusImg: require('../assets/images/parsalPlusImg.png'),
    truck: require('../assets/images/truck.png'),
    Bike: require('../assets/images/bike.png'),
    PackerMover: require('../assets/images/packerAndMovers.png'),
    India: require('../assets/images/india.png'),
    boxImg: require('../assets/images/boxImg.png'),
    CoinIcon: require('../assets/images/coin.png'),
    homeIcon: require('../assets/images/Home.png'),
    OrderIcon: require('../assets/images/Order.png'),
    UserIcon: require('../assets/images/User.png'),
    PaymentIcon: require('../assets/images/Payment.png'),
    activeHome: require('../assets/images/activeHome.png'),
    activeOrder: require('../assets/images/activeOrder.png'),
    activeUser: require('../assets/images/activeUser.png'),
    TrackParsalImg: require('../assets/images/trackParsalImg.png'),
    emptyImage: require('../assets/images/emptyBoxImage.png'),
    boxbackgound: require('../assets/images/boxImageBackground.png'),
    searchIcon: require('../assets/images/searchIcon.png'),
    arrowRight: require('../assets/images/arrowRight.png'),
    infoCircle: require('../assets/images/info-circle.png'),
    man: require('../assets/images/man.png'),
    optionRightArrow: require('../assets/images/optionRightArrow.png'),
    addressIcon: require('../assets/images/addressIcon.png'),
    helpIcon: require('../assets/images/helpIcon.png'),
    languageIcon: require('../assets/images/languageIcon.png'),
    logoutIcon: require('../assets/images/logoutIcon.png'),
    termsAndCondition: require('../assets/images/termsAndCondition.png'),
    sliderHorn: require('../assets/images/sliderHorn.png'),
    cameraImage: require('../assets/images/camera.png'),
    editPen: require('../assets/images/edit.png'),
    truckImage: require('../assets/images/truck_filled_icon.png'),
    threeWheelerImage: require('../assets/images/three-wheel.png'),
    twoWheelerImage: require('../assets/images/bike_fill_icon.png'),
    scooterImage: require('../assets/images/three-wheel.png'),
    vehicle: require('../assets/images/vehicle.png'),
    rideBike: require('../assets/images/ride-a-bike.png'),
    callImage:require('../assets/images/call.png'),
    cancelImage:require('../assets/images/cancel.png'),
    dhoniImage:require('../assets/images/dhoni.png'),
    hamburgerImage:require('../assets/images/more.png'),
    goback:require('../assets/images/back.png'),
    profileImage: require('../assets/images/profile.png'),
    earningImage: require('../assets/images/earning.png'), 
    paymentsImage: require('../assets/images/payments.png'), 
    loansImage: require('../assets/images/loan.png'),
    trainingImage: require('../assets/images/traning.png'), 
    notificationsImage: require('../assets/images/notifications.png'),
    privacyPolicyImage: require('../assets/images/privacyPolicy.png'), 
    ledgerImage: require('../assets/images/ledger.png'), 
    backWhite: require('../assets/images/backWhite.png'), 
    closeButton: require('../assets/images/close.png'), 







}